"""add_public_location_to_tasks

Revision ID: 18c39cf0d2bc
Revises: 08f64519ae82
Create Date: 2026-01-05 19:56:26.978918

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '18c39cf0d2bc'
down_revision = '08f64519ae82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('from_role', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('reviews', sa.Column('status', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_reviews_task_id'), 'reviews', ['task_id'], unique=False)
    op.create_unique_constraint('uq_review_task_from_user', 'reviews', ['task_id', 'from_user_id'])
    op.add_column('tasks', sa.Column('public_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('tasks', sa.Column('street', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('street_number', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('province', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('address_extra', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('place_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('formatted_address', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('access_notes', sa.Text(), nullable=True))
    op.create_index('idx_tasks_public_location', 'tasks', ['public_location'], unique=False, postgresql_using='gist')
    op.alter_column('users', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'readiness_status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'readiness_status',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_tasks_public_location', table_name='tasks', postgresql_using='gist')
    op.drop_column('tasks', 'access_notes')
    op.drop_column('tasks', 'formatted_address')
    op.drop_column('tasks', 'place_id')
    op.drop_column('tasks', 'address_extra')
    op.drop_column('tasks', 'province')
    op.drop_column('tasks', 'postal_code')
    op.drop_column('tasks', 'street_number')
    op.drop_column('tasks', 'street')
    op.drop_column('tasks', 'public_location')
    op.drop_constraint('uq_review_task_from_user', 'reviews', type_='unique')
    op.drop_index(op.f('ix_reviews_task_id'), table_name='reviews')
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'status')
    op.drop_column('reviews', 'tags')
    op.drop_column('reviews', 'from_role')
    # ### end Alembic commands ###
