"""phase_2_task_enhancements_retry

Revision ID: faea92d6142a
Revises: 94d1e38f72ff
Create Date: 2025-12-28 10:58:43.393646

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'faea92d6142a'
down_revision = '94d1e38f72ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('selected_offer_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('address_line', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('city', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('completion_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('dispute_open_until', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'task_offers', ['selected_offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tasks', 'dispute_open_until')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'completion_requested_at')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'assigned_at')
    op.drop_column('tasks', 'scheduled_at')
    op.drop_column('tasks', 'city')
    op.drop_column('tasks', 'address_line')
    op.drop_column('tasks', 'version')
    op.drop_column('tasks', 'selected_offer_id')
    # ### end Alembic commands ###
